name: test
on:
  push:
    branches:
      - master
      - cachetest
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./test_action 

  inline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1
      - name: Test
        run: go test -v .
