name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Test
        uses: ./test_action
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v2

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.23"
          - "1.22"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Test
        uses: docker/bake-action@v5
        with:
          targets: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v2
